// AUTOMATICALLY GENERATED by tools/generate-oids.js -- do not edit by hand.
// Regenerate with `npm run generate-oids` after adding or refreshing a MIB file.

export interface FamilyTable {
    /** Channel the rows are created under, for example `ports` */
    channel: string;
    /** Only polled when the user switched this branch on. Absent means always polled. */
    branch?: string;
    oid: string;
    /** OID of the column whose value names each row, preferred over the volatile SNMP index */
    rowName: string;
    /** OID of the column shown as `common.name` */
    label?: string;
    /** INDEX clause of the conceptual row, dot separated when it is composite */
    index: string;
    /** ioBroker state name to the OID of the column carrying it */
    columns: { [state: string]: string };
}

export interface FamilyOids {
    family: string;
    /** MIB file this entry was generated from */
    source: string;
    /** Datapoint to OID of a scalar object, polled as `<oid>.0` */
    scalars: { [topic: string]: string };
    /** Table name to its datapoints, polled as `<oid>.<rowIndex>` */
    rows: { [table: string]: { [topic: string]: string } };
    tables: { [table: string]: FamilyTable };
    /** Scalars of the optional branches, polled as `<oid>.0` when the branch is enabled */
    branches: { [branch: string]: { [state: string]: string } };
    /** Notification name to its OID, used to name an incoming trap */
    notifications: { [name: string]: string };
    /** Datapoints this family does not expose over SNMP */
    missing: string[];
}

export const FAMILY_OIDS: { [family: string]: FamilyOids } = {
    RUTC: {
        family: 'RUTC',
        source: 'RUTC_R_00.07.24.1.mib',
        scalars: {
            name: '1.3.6.1.4.1.48690.1.3',
            uptime: '1.3.6.1.4.1.48690.1.7',
        },
        rows: {
            modemTable: {
                connection: '1.3.6.1.4.1.48690.2.2.1.16',
                id: '1.3.6.1.4.1.48690.2.2.1.3',
                network: '1.3.6.1.4.1.48690.2.2.1.11',
                operator: '1.3.6.1.4.1.48690.2.2.1.13',
                signal: '1.3.6.1.4.1.48690.2.2.1.12',
                temperature: '1.3.6.1.4.1.48690.2.2.1.17',
                wan: '1.3.6.1.4.1.48690.2.2.1.24',
            },
        },
        tables: {
            hsSessionTable: {
                channel: 'hotspot',
                branch: 'hotspot',
                oid: '1.3.6.1.4.1.48690.5.6',
                rowName: '1.3.6.1.4.1.48690.5.6.1.2',
                index: 'hssIndex',
                columns: {
                    authorized: '1.3.6.1.4.1.48690.5.6.1.6',
                    ip: '1.3.6.1.4.1.48690.5.6.1.3',
                    user: '1.3.6.1.4.1.48690.5.6.1.5',
                },
            },
            ioTable: {
                channel: 'io',
                oid: '1.3.6.1.4.1.48690.6.2',
                rowName: '1.3.6.1.4.1.48690.6.2.1.2',
                label: '1.3.6.1.4.1.48690.6.2.1.3',
                index: 'ioIndex',
                columns: {
                    current: '1.3.6.1.4.1.48690.6.2.1.9',
                    percentage: '1.3.6.1.4.1.48690.6.2.1.10',
                    state: '1.3.6.1.4.1.48690.6.2.1.11',
                    type: '1.3.6.1.4.1.48690.6.2.1.4',
                },
            },
            mwan3Table: {
                channel: 'interfaces',
                oid: '1.3.6.1.4.1.48690.12.2',
                rowName: '1.3.6.1.4.1.48690.12.2.1.2',
                index: 'mwan3Index',
                columns: {
                    enabled: '1.3.6.1.4.1.48690.12.2.1.3',
                    status: '1.3.6.1.4.1.48690.12.2.1.5',
                    trackingHosts: '1.3.6.1.4.1.48690.12.2.1.6',
                    uptime: '1.3.6.1.4.1.48690.12.2.1.4',
                },
            },
            portTable: {
                channel: 'ports',
                oid: '1.3.6.1.4.1.48690.10.2',
                rowName: '1.3.6.1.4.1.48690.10.2.1.2',
                index: 'pIndex',
                columns: {
                    duplex: '1.3.6.1.4.1.48690.10.2.1.7',
                    speed: '1.3.6.1.4.1.48690.10.2.1.6',
                    state: '1.3.6.1.4.1.48690.10.2.1.5',
                },
            },
            radioTable: {
                channel: 'radios',
                branch: 'wireless',
                oid: '1.3.6.1.4.1.48690.7.2',
                rowName: '1.3.6.1.4.1.48690.7.2.1.2',
                index: 'radioIndex',
                columns: {
                    channel: '1.3.6.1.4.1.48690.7.2.1.5',
                    up: '1.3.6.1.4.1.48690.7.2.1.3',
                },
            },
            wIfaceTable: {
                channel: 'wifi',
                branch: 'wireless',
                oid: '1.3.6.1.4.1.48690.7.4',
                rowName: '1.3.6.1.4.1.48690.7.4.1.2',
                index: 'wIfaceIndex',
                columns: {
                    clients: '1.3.6.1.4.1.48690.7.4.1.6',
                    encryption: '1.3.6.1.4.1.48690.7.4.1.4',
                    hidden: '1.3.6.1.4.1.48690.7.4.1.3',
                    mode: '1.3.6.1.4.1.48690.7.4.1.5',
                },
            },
        },
        branches: {
            gps: {
                accuracy: '1.3.6.1.4.1.48690.3.3',
                fixTime: '1.3.6.1.4.1.48690.3.4',
                latitude: '1.3.6.1.4.1.48690.3.1',
                longitude: '1.3.6.1.4.1.48690.3.2',
                satellites: '1.3.6.1.4.1.48690.3.5',
            },
        },
        notifications: {
            clientConnectedNotification: '1.3.6.1.4.1.48690.4.3.1',
            clientDisconnectedNotification: '1.3.6.1.4.1.48690.4.3.2',
            digitalInputNotification: '1.3.6.1.4.1.48690.4.2.1',
            digitalOutputNotification: '1.3.6.1.4.1.48690.4.2.2',
            eventLogNotification: '1.3.6.1.4.1.48690.4.4.1',
            networkTypeNotification: '1.3.6.1.4.1.48690.4.1.2',
            signalChangeNotification: '1.3.6.1.4.1.48690.4.1.1',
        },
        missing: [],
    },
    TSW2: {
        family: 'TSW2',
        source: 'TSW2_R_00.01.10.mib',
        scalars: {
            name: '1.3.6.1.4.1.48690.1.3',
            uptime: '1.3.6.1.4.1.48690.1.7',
        },
        rows: {},
        tables: {
            portTable: {
                channel: 'ports',
                oid: '1.3.6.1.4.1.48690.10.2',
                rowName: '1.3.6.1.4.1.48690.10.2.1.2',
                index: 'pIndex',
                columns: {
                    duplex: '1.3.6.1.4.1.48690.10.2.1.7',
                    rxBytes: '1.3.6.1.4.1.48690.10.2.1.8',
                    rxRate: '1.3.6.1.4.1.48690.10.2.1.10',
                    speed: '1.3.6.1.4.1.48690.10.2.1.6',
                    state: '1.3.6.1.4.1.48690.10.2.1.5',
                    txBytes: '1.3.6.1.4.1.48690.10.2.1.9',
                    txRate: '1.3.6.1.4.1.48690.10.2.1.11',
                },
            },
        },
        branches: {},
        notifications: {},
        missing: ['connection', 'id', 'network', 'operator', 'signal', 'temperature', 'wan'],
    },
};
